In [1]:
import pandas as pd
import numpy as np

# Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism-preprocessed.csv')

In [3]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0                 30          0         2    1                          4  
1                 31          0         1    0                          0  
2                 31          0         0    0                          2  
3                 24          0         2    0                          4  
4                 30          0         2    1                          2  
..               ...        ...       ...  ...                        ...  
695               22          1         2    0                          8  
696               24          0         1    2                          3  
697               25          1         0    0                          8  
698               25          1         0    0                          2  
699               25          0         1    1                          2  

[700 rows x 15 columns]

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism']=targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# A comment on the targets

In [9]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours'], axis  = 1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Excessive Absenteeism  
0               30          0         2    1                      1  
1               31          0         1    0                      0  
2               31          0         0    0                      0  
3               24          0         2    0                      1  
4               30          0         2    1                      0

In [13]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

# Standardization

In [15]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [16]:
absenteeism_scaler.fit(unscaled_inputs)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [17]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [18]:
scaled_inputs.shape

(700, 14)

#  Split the data into train & test and shuffle

### Import the relevant module

In [19]:
from sklearn.model_selection import train_test_split

### Split

In [20]:
train_test_split(unscaled_inputs,targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
 261         1         0         0         0           10                5   
 655         1         0         0         0            2                6   
 394         0         0         0         1            3                0   
 123         0         0         0         1           12                3   
 88          0         0         0         1           11                2   
 ..        ...       ...       ...       ...          ...              ...   
 528         1         0         0         0           10                6   
 7           0         0         0         1            7                4   
 170         0         0         0         1            3                4   
 585         1         0         0         0            6                5   
 186         0         0         0         1           12                6   
 
      Transportation Expense  Distance to Work  Age  Daily Wor

In [21]:
x_train, x_test,y_train,y_test = train_test_split(unscaled_inputs,targets, train_size = 0.8, shuffle = True, random_state = 20)

In [22]:
print(x_train.shape)

(560, 14)


In [23]:
print(x_test.shape)

(140, 14)


# Logistic regression with sklearn

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the model

In [25]:
reg = LogisticRegression()

In [26]:
reg.fit(x_train,y_train)

C:\Users\c-rachithhe\AppData\Local\Continuum\anaconda3\envs\tensorflow2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
reg.score(x_train,y_train)

0.7571428571428571

## Manually find the accuracy

In [28]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [29]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [30]:
model_outputs ==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [31]:
np.sum(model_outputs ==y_train)

424

In [32]:
model_outputs.shape[0]

560

In [33]:
accuracy = np.sum(model_outputs ==y_train)/model_outputs.shape[0]

In [34]:
accuracy

0.7571428571428571

## Finding the intercepts and co-efficients

In [35]:
reg.intercept_

array([-1.59496175])

In [36]:
reg.coef_

array([[ 2.55315513,  0.78854875,  2.90407218,  0.54257534, -0.00799064,
        -0.04820571,  0.00836966, -0.00499754, -0.04072111, -0.00387032,
         0.04207289, -0.49063269,  0.31470321, -0.24199671]])

In [37]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work',
       'Age', 'Daily Work Load Average', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [38]:
feature_names = unscaled_inputs.columns.values

In [47]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_names)
summary_table

Feature name
0                  Reason_1
1                  Reason_2
2                  Reason_3
3                  Reason_4
4               Month Value
5           Day of the Week
6    Transportation Expense
7          Distance to Work
8                       Age
9   Daily Work Load Average
10          Body Mass Index
11                Education
12                 Children
13                      Pet

In [48]:
summary_table['Coefficients']=np.transpose(reg.coef_)

In [49]:
summary_table

Feature name  Coefficients
0                  Reason_1      2.553155
1                  Reason_2      0.788549
2                  Reason_3      2.904072
3                  Reason_4      0.542575
4               Month Value     -0.007991
5           Day of the Week     -0.048206
6    Transportation Expense      0.008370
7          Distance to Work     -0.004998
8                       Age     -0.040721
9   Daily Work Load Average     -0.003870
10          Body Mass Index      0.042073
11                Education     -0.490633
12                 Children      0.314703
13                      Pet     -0.241997

In [50]:
summary_table.index =summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()

In [51]:
summary_table

Feature name  Coefficients
0                 Intercept     -1.594962
1                  Reason_1      2.553155
2                  Reason_2      0.788549
3                  Reason_3      2.904072
4                  Reason_4      0.542575
5               Month Value     -0.007991
6           Day of the Week     -0.048206
7    Transportation Expense      0.008370
8          Distance to Work     -0.004998
9                       Age     -0.040721
10  Daily Work Load Average     -0.003870
11          Body Mass Index      0.042073
12                Education     -0.490633
13                 Children      0.314703
14                      Pet     -0.241997

## Interpreting the coefficients

In [53]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficients)

In [54]:
summary_table

Feature name  Coefficients  Odds_ratio
0                 Intercept     -1.594962    0.202916
1                  Reason_1      2.553155   12.847576
2                  Reason_2      0.788549    2.200201
3                  Reason_3      2.904072   18.248305
4                  Reason_4      0.542575    1.720432
5               Month Value     -0.007991    0.992041
6           Day of the Week     -0.048206    0.952938
7    Transportation Expense      0.008370    1.008405
8          Distance to Work     -0.004998    0.995015
9                       Age     -0.040721    0.960097
10  Daily Work Load Average     -0.003870    0.996137
11          Body Mass Index      0.042073    1.042970
12                Education     -0.490633    0.612239
13                 Children      0.314703    1.369853
14                      Pet     -0.241997    0.785059

In [56]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficients  Odds_ratio
3                  Reason_3      2.904072   18.248305
1                  Reason_1      2.553155   12.847576
2                  Reason_2      0.788549    2.200201
4                  Reason_4      0.542575    1.720432
13                 Children      0.314703    1.369853
11          Body Mass Index      0.042073    1.042970
7    Transportation Expense      0.008370    1.008405
10  Daily Work Load Average     -0.003870    0.996137
8          Distance to Work     -0.004998    0.995015
5               Month Value     -0.007991    0.992041
9                       Age     -0.040721    0.960097
6           Day of the Week     -0.048206    0.952938
14                      Pet     -0.241997    0.785059
12                Education     -0.490633    0.612239
0                 Intercept     -1.594962    0.202916

In [57]:
reg.score(x_test,y_test)

0.7285714285714285

In [58]:
predict_proba = reg.predict_proba(x_test)
predict_proba

array([[0.78036686, 0.21963314],
       [0.66362839, 0.33637161],
       [0.55235447, 0.44764553],
       [0.75565389, 0.24434611],
       [0.06526096, 0.93473904],
       [0.2545663 , 0.7454337 ],
       [0.24585032, 0.75414968],
       [0.11940134, 0.88059866],
       [0.73923389, 0.26076611],
       [0.756158  , 0.243842  ],
       [0.52036811, 0.47963189],
       [0.1705504 , 0.8294496 ],
       [0.07532594, 0.92467406],
       [0.69313337, 0.30686663],
       [0.26700571, 0.73299429],
       [0.49502243, 0.50497757],
       [0.53147173, 0.46852827],
       [0.65644564, 0.34355436],
       [0.36573618, 0.63426382],
       [0.05509038, 0.94490962],
       [0.72488846, 0.27511154],
       [0.74664384, 0.25335616],
       [0.39843897, 0.60156103],
       [0.4295715 , 0.5704285 ],
       [0.16344386, 0.83655614],
       [0.77776336, 0.22223664],
       [0.44597493, 0.55402507],
       [0.85451353, 0.14548647],
       [0.2376025 , 0.7623975 ],
       [0.737417  , 0.262583  ],
       [0.

In [59]:
predict_proba[:,1]

array([0.21963314, 0.33637161, 0.44764553, 0.24434611, 0.93473904,
       0.7454337 , 0.75414968, 0.88059866, 0.26076611, 0.243842  ,
       0.47963189, 0.8294496 , 0.92467406, 0.30686663, 0.73299429,
       0.50497757, 0.46852827, 0.34355436, 0.63426382, 0.94490962,
       0.27511154, 0.25335616, 0.60156103, 0.5704285 , 0.83655614,
       0.22223664, 0.55402507, 0.14548647, 0.7623975 , 0.262583  ,
       0.41769987, 0.73322047, 0.5782581 , 0.4691209 , 0.25335616,
       0.50813023, 0.30361334, 0.78911655, 0.40499256, 0.61265133,
       0.25144081, 0.46975716, 0.2521575 , 0.45653655, 0.71780589,
       0.71429281, 0.81933955, 0.21791822, 0.29023472, 0.18747279,
       0.54578112, 0.3257813 , 0.63591332, 0.28464938, 0.84915913,
       0.3862172 , 0.92109531, 0.36422871, 0.28479033, 0.29650313,
       0.75831436, 0.65625424, 0.34987565, 0.8401978 , 0.24649041,
       0.23954969, 0.12770661, 0.26217027, 0.80008447, 0.30405404,
       0.28280733, 0.25892415, 0.87298973, 0.38812184, 0.60190

In [60]:
import pickle

In [63]:
with open('model_with standardization','wb') as file:
    pickle.dump(reg,file)

In [64]:
with open('scaler_with standardization','wb') as file:
    pickle.dump(absenteeism_scaler,file)