In [1]:
import pandas as pd
import numpy as np

# Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism-preprocessed.csv')

In [3]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0                 30          0         2    1                          4  
1                 31          0         1    0                          0  
2                 31          0         0    0                          2  
3                 24          0         2    0                          4  
4                 30          0         2    1                          2  
..               ...        ...       ...  ...                        ...  
695               22          1         2    0                          8  
696               24          0         1    2                          3  
697               25          1         0    0                          8  
698               25          1         0    0                          2  
699               25          0         1    1                          2  

[700 rows x 15 columns]

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours']>data_preprocessed['Absenteeism Time in Hours'].median(),1,0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absenteeism']=targets

In [8]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0               30          0         2    1                          4   
1               31          0         1    0                          0   
2               31          0         0    0                          2   
3               24          0         2    0                          4   
4               30          0         2    1                          2   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

# A comment on the targets

In [9]:
targets.sum()/targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours','Day of the Week','Daily Work Load Average','Distance to Work'], axis  = 1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Age  Body Mass Index  Education  Children  Pet  \
0                     289   33               30          0         2    1   
1                     118   50               31          0         1    0   
2                     179   38               31          0         0    0   
3                     279   39               24          0         2    0   
4                     289   33               30          0         2    1   

   Excessive Absenteeism  
0                      1  
1                      0  
2                      0  
3                      1  
4                      0

In [13]:
data_with_targets.iloc[:,:-1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
0                       289   33               30          0         2    1  
1                       118   50               31          0         1    0  
2                       179   38               31          0         0    0  
3                       279   39               24          0         2    0  
4                       289   33               30          0         2    1  
..                      ...  ...              ...        ...       ...  ...  
695                     179   40               22          1         2    0  
696                     225   28               24          0         1    2  
697                     330   28               25          1         0    0  
698                     235   32               25          1         0    0  
699                     291   40               25          0         1    1  

[700 rows x 11 columns]

In [14]:
unscaled_inputs = data_with_targets.iloc[:,:-1]

# Standardization

In [15]:
from sklearn.preprocessing import StandardScaler

absenteeism_scaler = StandardScaler()

In [16]:
# import the libraries needed to create the Custom Scaler
# note that all of them are a part of the sklearn package
# moreover, one of them is actually the StandardScaler module, 
# so you can imagine that the Custom Scaler is build on it

from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

# create the Custom Scaler class

class CustomScaler(BaseEstimator,TransformerMixin): 
    
    # init or what information we need to declare a CustomScaler object
    # and what is calculated/declared as we do
    
    def __init__(self,columns,copy=True,with_mean=True,with_std=True):
        
        # scaler is nothing but a Standard Scaler object
        self.scaler = StandardScaler(copy,with_mean,with_std)
        # with some columns 'twist'
        self.columns = columns
        self.mean_ = None
        self.var_ = None
        
    
    # the fit method, which, again based on StandardScale
    
    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self
    
    # the transform method which does the actual scaling

    def transform(self, X, y=None, copy=None):
        
        # record the initial order of the columns
        init_col_order = X.columns
        
        # scale all features that you chose when creating the instance of the class
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        
        # declare a variable containing all information that was not scaled
        X_not_scaled = X.loc[:,~X.columns.isin(self.columns)]
        
        # return a data frame which contains all scaled features and all 'not scaled' features
        # use the original order (that you recorded in the beginning)
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]

In [17]:
columns_to_omit = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']

In [18]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [19]:
absenteeism_scaler = CustomScaler(columns_to_scale)

In [20]:
absenteeism_scaler.fit(unscaled_inputs)

CustomScaler(columns=['Month Value', 'Transportation Expense', 'Age',
                      'Body Mass Index', 'Children', 'Pet'],
             copy=None, with_mean=None, with_std=None)

In [21]:
scaled_inputs = absenteeism_scaler.transform(unscaled_inputs)

In [22]:
scaled_inputs.shape

(700, 11)

#  Split the data into train & test and shuffle

### Import the relevant module

In [23]:
from sklearn.model_selection import train_test_split

### Split

In [24]:
train_test_split(unscaled_inputs,targets)

[     Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
 663         0         0         0         1           10   
 376         0         0         0         1            2   
 535         0         0         0         1           10   
 170         0         0         0         1            3   
 250         0         0         1         0            7   
 ..        ...       ...       ...       ...          ...   
 466         0         0         0         1            7   
 584         0         0         0         1            1   
 253         0         0         1         0           11   
 586         0         0         0         1            6   
 342         0         0         0         1            5   
 
      Transportation Expense  Age  Body Mass Index  Education  Children  Pet  
 663                     361   28               27          0         1    4  
 376                     179   38               31          0         0    0  
 535                     179 

In [25]:
x_train, x_test,y_train,y_test = train_test_split(unscaled_inputs,targets, train_size = 0.8, shuffle = True, random_state = 20)

In [26]:
print(x_train.shape)

(560, 11)


In [27]:
print(x_test.shape)

(140, 11)


# Logistic regression with sklearn

In [28]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

## Training the model

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train,y_train)

C:\Users\c-rachithhe\AppData\Local\Continuum\anaconda3\envs\tensorflow2\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [31]:
reg.score(x_train,y_train)

0.7589285714285714

## Manually find the accuracy

In [32]:
model_outputs = reg.predict(x_train)
model_outputs

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [34]:
model_outputs ==y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True, False,  True,  True, False,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [35]:
np.sum(model_outputs ==y_train)

425

In [36]:
model_outputs.shape[0]

560

In [37]:
accuracy = np.sum(model_outputs ==y_train)/model_outputs.shape[0]

In [38]:
accuracy

0.7589285714285714

## Finding the intercepts and co-efficients

In [39]:
reg.intercept_

array([-2.33416626])

In [40]:
reg.coef_

array([[ 2.40401786,  0.7613923 ,  2.77293429,  0.45260937, -0.0106276 ,
         0.00761572, -0.0452722 ,  0.03719027, -0.45789794,  0.31094656,
        -0.23831848]])

In [41]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pet'], dtype=object)

In [42]:
feature_names = unscaled_inputs.columns.values

In [43]:
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_names)
summary_table

Feature name
0                 Reason_1
1                 Reason_2
2                 Reason_3
3                 Reason_4
4              Month Value
5   Transportation Expense
6                      Age
7          Body Mass Index
8                Education
9                 Children
10                     Pet

In [44]:
summary_table['Coefficients']=np.transpose(reg.coef_)

In [45]:
summary_table

Feature name  Coefficients
0                 Reason_1      2.404018
1                 Reason_2      0.761392
2                 Reason_3      2.772934
3                 Reason_4      0.452609
4              Month Value     -0.010628
5   Transportation Expense      0.007616
6                      Age     -0.045272
7          Body Mass Index      0.037190
8                Education     -0.457898
9                 Children      0.310947
10                     Pet     -0.238318

In [46]:
summary_table.index =summary_table.index+1
summary_table.loc[0]=['Intercept',reg.intercept_[0]]
summary_table = summary_table.sort_index()

In [47]:
summary_table

Feature name  Coefficients
0                Intercept     -2.334166
1                 Reason_1      2.404018
2                 Reason_2      0.761392
3                 Reason_3      2.772934
4                 Reason_4      0.452609
5              Month Value     -0.010628
6   Transportation Expense      0.007616
7                      Age     -0.045272
8          Body Mass Index      0.037190
9                Education     -0.457898
10                Children      0.310947
11                     Pet     -0.238318

## Interpreting the coefficients

In [48]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficients)

In [49]:
summary_table

Feature name  Coefficients  Odds_ratio
0                Intercept     -2.334166    0.096891
1                 Reason_1      2.404018   11.067555
2                 Reason_2      0.761392    2.141255
3                 Reason_3      2.772934   16.005530
4                 Reason_4      0.452609    1.572410
5              Month Value     -0.010628    0.989429
6   Transportation Expense      0.007616    1.007645
7                      Age     -0.045272    0.955737
8          Body Mass Index      0.037190    1.037890
9                Education     -0.457898    0.632612
10                Children      0.310947    1.364716
11                     Pet     -0.238318    0.787952

In [50]:
summary_table.sort_values('Odds_ratio', ascending=False)

Feature name  Coefficients  Odds_ratio
3                 Reason_3      2.772934   16.005530
1                 Reason_1      2.404018   11.067555
2                 Reason_2      0.761392    2.141255
4                 Reason_4      0.452609    1.572410
10                Children      0.310947    1.364716
8          Body Mass Index      0.037190    1.037890
6   Transportation Expense      0.007616    1.007645
5              Month Value     -0.010628    0.989429
7                      Age     -0.045272    0.955737
11                     Pet     -0.238318    0.787952
9                Education     -0.457898    0.632612
0                Intercept     -2.334166    0.096891

# Testing the model

In [51]:
reg.score(x_test,y_test)

0.7357142857142858

In [52]:
predict_proba = reg.predict_proba(x_test)
predict_proba

array([[0.76711002, 0.23288998],
       [0.63865558, 0.36134442],
       [0.60618259, 0.39381741],
       [0.75355643, 0.24644357],
       [0.07981164, 0.92018836],
       [0.30285535, 0.69714465],
       [0.26583462, 0.73416538],
       [0.15048192, 0.84951808],
       [0.68636043, 0.31363957],
       [0.76136565, 0.23863435],
       [0.53338569, 0.46661431],
       [0.21729053, 0.78270947],
       [0.05490359, 0.94509641],
       [0.75130206, 0.24869794],
       [0.33225863, 0.66774137],
       [0.55935013, 0.44064987],
       [0.53602978, 0.46397022],
       [0.52279203, 0.47720797],
       [0.42105519, 0.57894481],
       [0.0746418 , 0.9253582 ],
       [0.69543835, 0.30456165],
       [0.75355643, 0.24644357],
       [0.43527285, 0.56472715],
       [0.4457496 , 0.5542504 ],
       [0.17235196, 0.82764804],
       [0.68406811, 0.31593189],
       [0.52056844, 0.47943156],
       [0.84720072, 0.15279928],
       [0.23864119, 0.76135881],
       [0.75355643, 0.24644357],
       [0.

In [53]:
predict_proba.shape

(140, 2)

In [54]:
predict_proba[:,1]

array([0.23288998, 0.36134442, 0.39381741, 0.24644357, 0.92018836,
       0.69714465, 0.73416538, 0.84951808, 0.31363957, 0.23863435,
       0.46661431, 0.78270947, 0.94509641, 0.24869794, 0.66774137,
       0.44064987, 0.46397022, 0.47720797, 0.57894481, 0.9253582 ,
       0.30456165, 0.24644357, 0.56472715, 0.5542504 , 0.82764804,
       0.31593189, 0.47943156, 0.15279928, 0.76135881, 0.24644357,
       0.37121142, 0.77043348, 0.68121138, 0.46132815, 0.24644357,
       0.5491298 , 0.31135631, 0.82898656, 0.34225432, 0.62093072,
       0.24842253, 0.56981745, 0.32054341, 0.51022137, 0.70298061,
       0.65232756, 0.77395867, 0.24251759, 0.24691209, 0.25041209,
       0.54886493, 0.32439541, 0.69714465, 0.25692523, 0.79929193,
       0.35645385, 0.89610719, 0.3296032 , 0.2967864 , 0.29457317,
       0.69626113, 0.6903711 , 0.32259687, 0.81993561, 0.2732771 ,
       0.23479401, 0.14937875, 0.30908219, 0.77319322, 0.24084011,
       0.32519025, 0.30928841, 0.81898517, 0.34705513, 0.55963

# save the model

In [55]:
import pickle

In [56]:
with open('model','wb') as file:
    pickle.dump(reg,file)

In [57]:
with open('scaler','wb') as file:
    pickle.dump(absenteeism_scaler,file)